'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import { createClient } from './client';
import { useAuth } from './auth-context';
import { captureError } from '@/lib/capture-error';

export interface LoanRow {
  id: string;
  member_id: string;
  loan_number: string;
  loan_type: string;
  amount: number;
  interest_rate: number;
  term_months: number;
  status: string;
  purpose: string | null;
  collateral: string | null;
  approved_by: string | null;
  approved_at: string | null;
  disbursed_at: string | null;
  due_date: string | null;
  amount_repaid: number;
  created_at: string;
  updated_at: string;
}

export function useLoans() {
  const { user } = useAuth();
  const supabase = useMemo(() => createClient(), []);
  const [loans, setLoans] = useState<LoanRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchLoans = useCallback(async () => {
    if (!user) {
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const { data, error: fetchError } = await supabase
        .from('loans')
        .select('*')
        .order('created_at', { ascending: false });

      if (fetchError) {
        captureError('useLoans.fetch', fetchError);
        setError(fetchError.message);
        setLoans([]);
      } else {
        setLoans((data || []) as LoanRow[]);
      }
    } catch (err) {
      captureError('useLoans.exception', err);
      setError(err instanceof Error ? err.message : 'Unknown error');
      setLoans([]);
    } finally {
      setLoading(false);
    }
  }, [supabase, user]);

  useEffect(() => {
    fetchLoans();
  }, [fetchLoans]);

  const applyForLoan = useCallback(async (loanData: {
    loan_type: string;
    amount: number;
    interest_rate: number;
    term_months: number;
    purpose?: string;
    collateral?: string;
  }) => {
    try {
      const { data: member } = await supabase
        .from('members')
        .select('id')
        .eq('profile_id', user?.id)
        .single();

      if (!member) {
        return { data: null, error: { message: 'No member record found. Please complete your membership application first.' } };
      }

      const { data, error: insertError } = await supabase
        .from('loans')
        .insert({
          member_id: member.id,
          loan_type: loanData.loan_type,
          amount: loanData.amount,
          interest_rate: loanData.interest_rate,
          term_months: loanData.term_months,
          purpose: loanData.purpose || null,
          collateral: loanData.collateral || null,
          status: 'submitted',
          loan_number: '', // Auto-generated by trigger
        })
        .select()
        .single();

      if (!insertError && data) {
        setLoans(prev => [data as LoanRow, ...prev]);

        // Fire server-side notifications (email + admin + automations)
        fetch('/api/loans/notify', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ loan_id: (data as LoanRow).id }),
        }).catch(() => { /* best-effort */ });
      }

      return { data, error: insertError };
    } catch (err) {
      captureError('useLoans.applyForLoan', err);
      return { data: null, error: { message: err instanceof Error ? err.message : 'Unknown error' } };
    }
  }, [supabase, user]);

  const stats = {
    total: loans.length,
    active: loans.filter(l => ['approved', 'disbursed', 'repaying'].includes(l.status)).length,
    pending: loans.filter(l => ['draft', 'submitted', 'under_review'].includes(l.status)).length,
    completed: loans.filter(l => l.status === 'completed').length,
    totalAmount: loans.reduce((s, l) => s + Number(l.amount), 0),
    totalRepaid: loans.reduce((s, l) => s + Number(l.amount_repaid), 0),
  };

  return { loans, loading, error, stats, applyForLoan, refetch: fetchLoans };
}
