'use client';

import { useState, useEffect, useCallback } from 'react';
import { createClient } from './client';
import { useAuth } from './auth-context';

export interface LoanRow {
  id: string;
  member_id: string;
  loan_number: string;
  loan_type: string;
  amount: number;
  interest_rate: number;
  term_months: number;
  status: string;
  purpose: string | null;
  collateral: string | null;
  approved_by: string | null;
  approved_at: string | null;
  disbursed_at: string | null;
  due_date: string | null;
  amount_repaid: number;
  created_at: string;
  updated_at: string;
}

export function useLoans() {
  const { user } = useAuth();
  const [loans, setLoans] = useState<LoanRow[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchLoans = useCallback(async () => {
    if (!user) return;
    setLoading(true);
    const supabase = createClient();

    // Fetch loans — for members, filter by their member record
    // For admins, this would fetch all (handled by RLS or separate admin hook)
    const { data, error } = await supabase
      .from('loans')
      .select('*')
      .order('created_at', { ascending: false });

    if (!error && data) {
      setLoans(data as LoanRow[]);
    }
    setLoading(false);
  }, [user]);

  useEffect(() => {
    fetchLoans();
  }, [fetchLoans]);

  const applyForLoan = useCallback(async (loanData: {
    loan_type: string;
    amount: number;
    interest_rate: number;
    term_months: number;
    purpose?: string;
    collateral?: string;
  }) => {
    const supabase = createClient();

    // First get the member record for this user
    const { data: member } = await supabase
      .from('members')
      .select('id')
      .eq('profile_id', user?.id)
      .single();

    if (!member) {
      return { error: { message: 'No member record found. Please complete your membership application first.' } };
    }

    const { data, error } = await supabase
      .from('loans')
      .insert({
        member_id: member.id,
        loan_type: loanData.loan_type,
        amount: loanData.amount,
        interest_rate: loanData.interest_rate,
        term_months: loanData.term_months,
        purpose: loanData.purpose || null,
        collateral: loanData.collateral || null,
        status: 'submitted',
        loan_number: '', // Auto-generated by trigger
      })
      .select()
      .single();

    if (!error && data) {
      setLoans(prev => [data as LoanRow, ...prev]);
    }

    return { data, error };
  }, [user]);

  const stats = {
    total: loans.length,
    active: loans.filter(l => ['approved', 'disbursed', 'repaying'].includes(l.status)).length,
    pending: loans.filter(l => ['draft', 'submitted', 'under_review'].includes(l.status)).length,
    completed: loans.filter(l => l.status === 'completed').length,
    totalAmount: loans.reduce((s, l) => s + Number(l.amount), 0),
    totalRepaid: loans.reduce((s, l) => s + Number(l.amount_repaid), 0),
  };

  return { loans, loading, stats, applyForLoan, refetch: fetchLoans };
}
