const { createClient } = require('@supabase/supabase-js');

const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

const posts = [
  { title: 'AFU Launches Across 9 African Countries', slug: 'afu-launches-9-countries', excerpt: 'The African Farming Union officially launches operations across the continent.', content: 'The African Farming Union has officially launched its pan-African agricultural platform across 9 countries. Our mission is simple: by farmers, for farmers.\n\nWith over 50 members already signed up, AFU is building the infrastructure that African agriculture has been missing.\n\nKey services now available:\n- Input financing and crop development loans\n- Parametric and traditional crop insurance\n- Online marketplace for seeds, fertilizer, and equipment\n- Training courses and agricultural knowledge base\n- Commodity trading desk\n- Warehouse receipt financing', cover_image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200&h=600&fit=crop', category: 'news', tags: ['launch', 'expansion'], status: 'published', published_at: '2026-03-20T10:00:00Z' },
  { title: 'How Smallholder Farmers Can Access Input Finance', slug: 'smallholder-input-finance', excerpt: 'A practical guide to accessing seeds, fertilizer, and equipment on credit.', content: 'Access to quality inputs is the biggest challenge facing smallholder farmers. AFU Input Finance allows members to purchase inputs on credit with repayment tied to harvest.\n\n1. Join AFU (free tier available)\n2. Complete your farm profile\n3. Browse the marketplace\n4. Apply for input finance\n5. Receive inputs delivered\n6. Repay after harvest\n\nInterest rates start at 8% per season.', cover_image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=1200&h=600&fit=crop', category: 'guides', tags: ['financing', 'inputs'], status: 'published', published_at: '2026-03-22T10:00:00Z' },
  { title: 'Understanding Crop Insurance in Africa', slug: 'understanding-crop-insurance', excerpt: 'Why every farmer needs crop insurance and how parametric insurance works.', content: 'Climate change makes African farming unpredictable. AFU offers two types:\n\nTraditional Insurance: Assessor visits after damage.\nParametric Insurance: Payouts triggered automatically by weather data.\n\nParametric is powerful for smallholders because payouts arrive within days, not months.', cover_image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=1200&h=600&fit=crop', category: 'guides', tags: ['insurance', 'climate'], status: 'published', published_at: '2026-03-25T10:00:00Z' },
  { title: 'Coffee Trading: From Farm to Export', slug: 'coffee-trading-farm-to-export', excerpt: 'How AFU connects African coffee farmers directly to international buyers.', content: 'Africa produces some of the finest coffee in the world. Yet most farmers receive a fraction of the export price.\n\nAFU Trading Desk connects farmers directly to buyers. Farmers list their coffee, set minimum prices, and buyers submit quotes.\n\nResult: farmers typically earn 20-40% more than selling to middlemen.', cover_image: 'https://images.unsplash.com/photo-1447933601403-56dc2df0e811?w=1200&h=600&fit=crop', category: 'trading', tags: ['coffee', 'export'], status: 'published', published_at: '2026-03-28T10:00:00Z' },
  { title: 'Ambassador Program: Earn While You Grow', slug: 'ambassador-program-earn', excerpt: 'Join the AFU Ambassador Program and earn commissions for referrals.', content: 'As an ambassador, you get a unique referral link. Share it and earn:\n\n- Membership fees: 10% recurring\n- Fundraising: 2-10% depending on amount\n- Tier progression: Bronze (2%) to Diamond (10%)\n\nApply at africanfarmingunion.org/ambassadors', cover_image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&h=600&fit=crop', category: 'programs', tags: ['ambassador', 'referral'], status: 'published', published_at: '2026-03-30T10:00:00Z' },
  { title: 'Warehouse Receipt Financing Explained', slug: 'warehouse-receipt-financing', excerpt: 'Use your stored harvest as collateral to access immediate cash.', content: 'Deliver your crop to an AFU warehouse. Get a receipt. Borrow up to 70% of market value.\n\nInstead of selling at harvest lows, store and sell later when prices rise 30-50% higher.\n\nAFU warehouses across all 9 countries with quality grading, insurance, and financing built in.', cover_image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200&h=600&fit=crop', category: 'guides', tags: ['warehouse', 'financing'], status: 'published', published_at: '2026-04-01T10:00:00Z' },
  { title: 'Young Farmers: The Future of African Agriculture', slug: 'young-farmers-future', excerpt: 'How AFU supports the next generation with training and startup capital.', content: 'The average age of an African farmer is 60. AFU Young Farmers program provides:\n- Free training courses\n- Mentorship from experienced farmers\n- Startup financing at reduced rates\n- Access to precision agriculture tools\n- Community of young agricultural entrepreneurs', cover_image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?w=1200&h=600&fit=crop', category: 'programs', tags: ['youth', 'training'], status: 'published', published_at: '2026-04-02T10:00:00Z' },
  { title: 'Maize Market Update: Prices Rise Across East Africa', slug: 'maize-market-update-april', excerpt: 'Maize prices up 15% across Kenya, Tanzania, and Uganda.', content: 'Maize prices across East Africa have risen sharply in April 2026.\n\nCurrent prices:\n- Kenya: KES 4,500/90kg bag (up 12%)\n- Tanzania: TZS 45,000/100kg bag (up 18%)\n- Uganda: UGX 120,000/100kg bag (up 15%)\n\nFarmers who used warehouse receipt financing are now selling at significantly higher prices.', cover_image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=1200&h=600&fit=crop', category: 'market', tags: ['maize', 'prices'], status: 'published', published_at: '2026-04-03T10:00:00Z' },
  { title: 'How to Join AFU: A Step-by-Step Guide', slug: 'how-to-join-afu', excerpt: 'Everything you need to know about joining the African Farming Union.', content: 'Step 1: Visit africanfarmingunion.org/memberships\nStep 2: Choose your tier (Free, Smallholder, Commercial, Enterprise, Partner)\nStep 3: Fill in your details\nStep 4: Application reviewed within 3-5 days\nStep 5: Receive login credentials via email\n\nOnce approved, access marketplace, financing, insurance, training, and the full AFU ecosystem.', cover_image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&h=600&fit=crop', category: 'guides', tags: ['membership', 'getting-started'], status: 'published', published_at: '2026-04-04T10:00:00Z' },
  { title: 'Sustainable Farming Practices That Increase Yield', slug: 'sustainable-farming-practices', excerpt: 'Conservation agriculture techniques that boost yields while protecting soil.', content: 'Key practices:\n1. Minimum Tillage: Cut fuel costs by 40%\n2. Crop Rotation: Reduce fertilizer needs by 30%\n3. Mulching: Reduce water loss by 50%\n4. Intercropping: Maximize land use\n5. Integrated Pest Management: Cut chemical costs by 60%\n\nFarmers adopting these practices see 20-40% yield increases within two seasons.', cover_image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=1200&h=600&fit=crop', category: 'guides', tags: ['sustainability', 'yields'], status: 'published', published_at: '2026-04-05T10:00:00Z' },
];

async function seed() {
  const { data, error } = await sb.from('blog_posts').insert(posts).select('id, title');
  if (error) {
    console.log('Error:', error.message);
    if (error.message.includes('schema cache') || error.message.includes('not found')) {
      console.log('Run migration 041 on Supabase first, then re-run this script.');
    }
  } else {
    console.log('Seeded', data.length, 'blog posts:');
    data.forEach(p => console.log(' -', p.title));
  }
}

seed();
