-- ============================================================================
-- AFU JOB LISTINGS: Full Update Script
-- Updates all 33 job listings with org-chart ordering and rich descriptions
-- Run in Supabase SQL Editor
-- ============================================================================

-- Step 1: Add missing columns that the frontend expects but the DB schema lacks
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS requirements TEXT;
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS skills TEXT[] DEFAULT '{}';
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS experience_years INTEGER DEFAULT 0;
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS education TEXT;

-- ============================================================================
-- TIER 1 — C-SUITE (positions 33–29, newest timestamps)
-- ============================================================================

-- 1. CFO (position 33)
UPDATE job_listings SET
  created_at = '2026-03-25T00:33:00Z',
  description = E'AFU is seeking an experienced CFO to build and lead our financial operations across 10 African countries. You will manage a $500M seed deployment, establish treasury operations, and build investor-grade financial reporting from day one. This is not a corporate finance role \u2014 you will be building financial infrastructure for agricultural lending, insurance, trade finance, and mobile money operations in frontier markets.\n\nResponsibilities:\n\u2022 Build and manage financial controls, treasury, and fund accounting for $500M+ in capital deployment\n\u2022 Establish investor reporting cadence (monthly, quarterly, annual) to institutional standards\n\u2022 Oversee multi-currency operations across 10 African currencies plus USD\n\u2022 Design and implement financial models for agricultural lending, crop insurance, and trade finance\n\u2022 Manage relationships with auditors, tax advisors, and regulators across all jurisdictions\n\u2022 Build the finance team from scratch \u2014 hire country finance managers and central accounting staff\n\u2022 Coordinate with Hamilton Reserve Bank on trade finance and banking operations\n\u2022 Manage mobile money float and liquidity across M-Pesa, EcoCash, MTN MoMo, Orange Money, Airtel\n\u2022 Prepare for Series A and subsequent funding rounds\n\u2022 Oversee cooperative financial governance (51% farmer-owned structures)',
  requirements = E'Requirements:\n\u2022 10+ years in finance, with at least 5 years as CFO or VP Finance\n\u2022 Experience in African markets \u2014 ideally across multiple jurisdictions\n\u2022 Deep understanding of agricultural finance, microfinance, or development finance\n\u2022 Experience with mobile money ecosystems and multi-currency treasury management\n\u2022 Strong understanding of cooperative financial structures\n\u2022 CPA, CA, ACCA, or equivalent professional qualification\n\u2022 Experience managing $100M+ in assets or fund deployment\n\u2022 Track record of building finance teams in high-growth environments\n\nNice to Have:\n\u2022 Experience with DFIs (IFC, AfDB, CDC, FMO) or impact investment funds\n\u2022 Knowledge of Lloyd\u2019s of London coverholder financial requirements\n\u2022 Experience with blockchain/tokenized assets accounting\n\u2022 Understanding of SBLC and Letter of Credit documentation\n\u2022 Fluency in French or Portuguese (for West/East Africa expansion)',
  skills = ARRAY['Financial strategy', 'Treasury management', 'Multi-currency operations', 'Investor reporting', 'Agricultural finance', 'Fund accounting', 'Mobile money'],
  experience_years = 10,
  education = E'CPA, CA, ACCA, or equivalent professional qualification'
WHERE title = 'CFO';

-- 2. CRO (position 32)
UPDATE job_listings SET
  created_at = '2026-03-25T00:32:00Z',
  description = E'AFU is building Africa\u2019s first integrated agricultural insurance platform as a Lloyd\u2019s of London coverholder. We need a CRO who can build credit risk models for smallholder lending, design parametric insurance products, and satisfy Lloyd\u2019s regulatory requirements from day one. You will be the bridge between traditional insurance/risk management and cutting-edge agritech.\n\nResponsibilities:\n\u2022 Build and maintain credit risk scoring models for smallholder and commercial farm lending\n\u2022 Design parametric and index-based crop insurance products with Lloyd\u2019s underwriting capacity\n\u2022 Establish and manage the Lloyd\u2019s coverholder compliance framework\n\u2022 Develop fraud detection and prevention systems across all financial products\n\u2022 Build risk appetite frameworks for agricultural lending across 10 countries\n\u2022 Oversee weather data integration for parametric insurance triggers\n\u2022 Manage reinsurance relationships and treaty negotiations\n\u2022 Implement portfolio risk monitoring and early warning systems\n\u2022 Design credit scorecards using alternative data (satellite imagery, mobile money history, farm telemetry)\n\u2022 Report to the Board on risk exposure, capital adequacy, and insurance performance',
  requirements = E'Requirements:\n\u2022 10+ years in risk management, insurance, or credit risk\n\u2022 Deep understanding of agricultural risk \u2014 crop insurance, weather derivatives, or agri-lending\n\u2022 Experience with Lloyd\u2019s of London or coverholder operations\n\u2022 Proven ability to build credit scoring models, ideally for underbanked populations\n\u2022 Understanding of parametric/index-based insurance products\n\u2022 Experience in African markets or emerging market risk management\n\u2022 Professional qualifications in risk management (FRM, CRM) or actuarial science\n\nNice to Have:\n\u2022 Actuarial background or ACII qualification\n\u2022 Experience with satellite data or remote sensing for risk assessment\n\u2022 Knowledge of mobile money data for creditworthiness assessment\n\u2022 Understanding of blockchain-based insurance or smart contract triggers',
  skills = ARRAY['Credit risk modelling', 'Parametric insurance', 'Lloyd''s compliance', 'Agricultural risk', 'Fraud detection', 'Reinsurance'],
  experience_years = 10,
  education = E'Actuarial science, Risk Management, or related degree with FRM/CRM qualification'
WHERE title = 'CRO';

-- 3. CLO (position 31)
UPDATE job_listings SET
  created_at = '2026-03-25T00:31:00Z',
  description = E'AFU operates across 10 African jurisdictions with a Netherlands Foundation holding structure, Mauritius operating company, country-level cooperatives, and Lloyd\u2019s coverholder status. We need a CLO who can navigate this multi-layered corporate structure while keeping things simple enough to move fast. You\u2019ll handle everything from cooperative law to trade finance contracts to IP protection.\n\nResponsibilities:\n\u2022 Establish and manage the Netherlands Foundation (Stichting) governance\n\u2022 Register and govern farmer-owned cooperatives across 10 countries (51% farmer ownership)\n\u2022 Draft and manage all commercial agreements: offtake, supply, financing, insurance, partnership\n\u2022 Ensure Lloyd\u2019s coverholder regulatory compliance\n\u2022 Manage IP portfolio including platform technology, brand, and trade secrets\n\u2022 Navigate agricultural, financial services, and cooperative regulations across 10 jurisdictions\n\u2022 Advise on Hamilton Reserve Bank partnership and white-label banking regulatory requirements\n\u2022 Draft investor documents, SAFEs, convertible notes, and equity agreements\n\u2022 Oversee KYC/AML compliance framework across all countries\n\u2022 Manage trade finance legal documentation (SBLCs, Letters of Credit, bills of lading)\n\u2022 Advise on blockchain regulatory landscape (token issuance, stablecoin compliance)',
  requirements = E'Requirements:\n\u2022 12+ years legal experience, with 5+ years in African or multi-jurisdiction practice\n\u2022 Experience with cooperative law, agricultural law, or microfinance regulation\n\u2022 Understanding of Dutch Foundation (Stichting) or similar structures\n\u2022 Experience with financial services licensing across African jurisdictions\n\u2022 Strong contract drafting and negotiation skills\n\u2022 Experience advising startups or high-growth companies\n\u2022 LLB/JD with admission to at least one relevant jurisdiction\n\nNice to Have:\n\u2022 Experience with Lloyd\u2019s of London regulatory requirements\n\u2022 Knowledge of Mauritius Global Business License structures\n\u2022 Understanding of blockchain/token regulatory landscape\n\u2022 Experience with DFI or development finance legal frameworks\n\u2022 Fluency in French or Portuguese',
  skills = ARRAY['Corporate law', 'Financial regulation', 'Cooperative law', 'Trade finance', 'Multi-jurisdictional', 'IP protection'],
  experience_years = 12,
  education = E'LLB/JD with admission to relevant jurisdiction'
WHERE title = 'CLO';

-- 4. CCO (position 30)
UPDATE job_listings SET
  created_at = '2026-03-25T00:30:00Z',
  description = E'AFU guarantees offtake for every farmer on our platform. We need a CCO who can build and manage the buyer network, negotiate export contracts, manage commodity pricing, and run the trade desk. You are the person who ensures that when a farmer grows it, there\u2019s a buyer waiting.\n\nResponsibilities:\n\u2022 Build and manage the offtake buyer network across domestic, regional, and international markets\n\u2022 Negotiate export contracts for high-value crops (blueberries, macadamia, avocado, specialty coffee)\n\u2022 Establish commodity pricing frameworks and market intelligence systems\n\u2022 Manage the AFU trade desk \u2014 matching supply from 10 countries with buyer demand\n\u2022 Coordinate with the trade finance team on SBLC and LC requirements for export deals\n\u2022 Develop retail and wholesale distribution channels (AFU Fresh marketplace)\n\u2022 Build strategic partnerships with food processors, retailers, and commodity traders\n\u2022 Lead market entry analysis for new crops and new geographies\n\u2022 Manage quality standards and compliance for export markets (GlobalGAP, HACCP, organic)\n\u2022 Build and manage the commercial team across all countries',
  requirements = E'Requirements:\n\u2022 10+ years in agricultural commodity trading, export, or agri-business development\n\u2022 Deep network of buyers in European, Middle Eastern, or Asian commodity markets\n\u2022 Experience in African agricultural exports\n\u2022 Understanding of trade finance instruments (LCs, SBLCs, warehouse receipts)\n\u2022 Track record of building and scaling commercial operations\n\u2022 Knowledge of food safety and export certification requirements\n\u2022 Willingness to travel extensively across Africa\n\nNice to Have:\n\u2022 Existing relationships with European supermarket buyers or commodity traders\n\u2022 Experience with blueberry, macadamia, or high-value horticultural exports\n\u2022 Knowledge of fair trade, organic, or sustainability certifications\n\u2022 Understanding of agricultural blockchain and traceability',
  skills = ARRAY['Commodity trading', 'Export management', 'Buyer relationships', 'Pricing strategy', 'Trade finance', 'Quality standards'],
  experience_years = 10,
  education = E'Business, Agriculture, or related degree'
WHERE title = 'CCO';

-- 5. CPO (position 29)
UPDATE job_listings SET
  created_at = '2026-03-25T00:29:00Z',
  description = E'AFU will grow from 2 people to 1,000+ across 10 African countries in 5 years. We need a CPO who can build a talent engine that recruits, develops, and retains world-class talent in some of the most challenging hiring markets on the continent. You\u2019ll build the culture that makes AFU the employer of choice in African agritech.\n\nResponsibilities:\n\u2022 Build the entire HR function from scratch \u2014 policies, processes, systems, culture\n\u2022 Design and execute hiring strategies across 10 African countries and multiple languages\n\u2022 Establish competitive compensation and benefits structures for each market\n\u2022 Navigate labor law compliance across 10+ jurisdictions\n\u2022 Build the AFU Jobs marketplace and internal recruitment engine\n\u2022 Design onboarding and training programs for all levels (HQ to field staff)\n\u2022 Establish performance management, career development, and succession planning\n\u2022 Build a distributed team culture that works across time zones and cultures\n\u2022 Manage payroll operations across multiple currencies and payment methods\n\u2022 Champion diversity, equity, and inclusion across all operations',
  requirements = E'Requirements:\n\u2022 8+ years in HR/People leadership, with experience building teams in Africa\n\u2022 Experience scaling from startup to 500+ employees\n\u2022 Deep understanding of labor law across at least 3 African jurisdictions\n\u2022 Experience with remote/distributed team management\n\u2022 Strong employer branding and talent acquisition skills\n\u2022 Understanding of agricultural or field-based workforce management\n\u2022 CIPD, SHRM, or equivalent qualification\n\nNice to Have:\n\u2022 Experience hiring field-based agricultural staff at scale\n\u2022 Knowledge of cooperative workforce structures\n\u2022 Fluency in multiple African languages or French/Portuguese\n\u2022 Experience with payroll in mobile-money-heavy markets',
  skills = ARRAY['Talent acquisition', 'Compensation design', 'African labour law', 'Culture building', 'Organisational design', 'Payroll operations'],
  experience_years = 8,
  education = E'HR, Business, or related degree with CIPD/SHRM qualification'
WHERE title = 'CPO';

-- ============================================================================
-- TIER 2 — VPs & DIRECTORS (positions 28–18)
-- ============================================================================

-- 6. VP Engineering (position 28)
UPDATE job_listings SET
  created_at = '2026-03-25T00:28:00Z',
  description = E'AFU\u2019s platform is a 200+ page Next.js application with 40+ database tables, AI integration, real-time data, mobile money APIs, and blockchain components. We need a VP Engineering to take ownership of the engineering team, establish best practices, and scale the platform to handle millions of farmers across 10 countries.\n\nResponsibilities:\n\u2022 Lead and grow the engineering team from 2 to 25+ developers\n\u2022 Own sprint planning, code reviews, architecture decisions, and technical debt management\n\u2022 Scale the platform for multi-country, multi-currency, multi-language operations\n\u2022 Build and maintain mobile applications (React Native or Flutter)\n\u2022 Implement real-time systems for market prices, weather data, and notifications\n\u2022 Ensure 99.9% uptime with proper monitoring, alerting, and incident response\n\u2022 Establish engineering hiring standards and technical interview processes\n\u2022 Manage integrations with external APIs (mobile money, banking, satellite, weather)\n\u2022 Implement automated testing, CI/CD, and deployment pipelines\n\u2022 Collaborate with Product on feature prioritization and technical feasibility',
  requirements = E'Requirements:\n\u2022 8+ years software engineering, with 3+ years in engineering leadership\n\u2022 Expert in TypeScript, React/Next.js, and Node.js\n\u2022 Strong experience with PostgreSQL and Supabase or similar\n\u2022 Experience building multi-tenant SaaS platforms at scale\n\u2022 Track record of hiring and mentoring engineering teams\n\u2022 Understanding of mobile-first development for low-bandwidth environments\n\u2022 Experience with CI/CD, automated testing, and DevOps practices\n\nNice to Have:\n\u2022 Experience with African fintech or agritech platforms\n\u2022 Knowledge of mobile money API integrations (M-Pesa, EcoCash)\n\u2022 Experience with AI/ML integration in production systems\n\u2022 Blockchain/smart contract development experience\n\u2022 Experience building offline-first or low-connectivity applications',
  skills = ARRAY['TypeScript', 'React/Next.js', 'PostgreSQL', 'Team leadership', 'System architecture', 'CI/CD', 'Mobile development'],
  experience_years = 8,
  education = E'Computer Science or equivalent'
WHERE title = 'VP Engineering';

-- 7. VP Product (position 27)
UPDATE job_listings SET
  created_at = '2026-03-25T00:27:00Z',
  description = E'AFU\u2019s platform serves everyone from illiterate smallholder farmers using basic smartphones to commercial farm managers running 1,000+ hectare operations. We need a VP Product who can build products that work for BOTH ends of this spectrum while maintaining a single coherent platform.\n\nResponsibilities:\n\u2022 Own the product roadmap and feature prioritization across 5 portals\n\u2022 Conduct user research with farmers, field staff, and administrators across Africa\n\u2022 Design the progressive disclosure system (Seedling\u2192Pioneer tier unlock)\n\u2022 Ensure products work on low-end Android devices with intermittent connectivity\n\u2022 Build product analytics and track farmer engagement, retention, and outcomes\n\u2022 Manage the UX/UI design team and establish design system standards\n\u2022 Coordinate multilingual product releases (English, Shona, Swahili, French, Portuguese)\n\u2022 Design farmer onboarding flows that work for low-literacy users\n\u2022 Build A/B testing frameworks for feature optimization\n\u2022 Translate commercial requirements into product specifications',
  requirements = E'Requirements:\n\u2022 7+ years in product management, with 3+ years leading product teams\n\u2022 Experience designing for emerging markets or low-literacy users\n\u2022 Strong UX sensibility with ability to design and prototype\n\u2022 Data-driven approach to product decisions\n\u2022 Experience with B2B2C or marketplace platforms\n\u2022 Willingness to spend time in the field with actual farmers\n\u2022 Understanding of mobile-first product design\n\nNice to Have:\n\u2022 Experience with agricultural technology or farmer-facing products\n\u2022 Knowledge of progressive web apps and offline-first design\n\u2022 Experience with fintech product design (lending, insurance, payments)\n\u2022 Fluency in an African language\n\u2022 Experience with voice-based or USSD interfaces',
  skills = ARRAY['Product strategy', 'UX design', 'Multilingual products', 'Offline-first design', 'Agile', 'User research'],
  experience_years = 7,
  education = E'Product Management, Design, or related field'
WHERE title = 'VP Product';

-- 8. Director of Data & AI (position 26)
UPDATE job_listings SET
  created_at = '2026-03-25T00:26:00Z',
  description = E'AFU uses AI across the platform: crop disease detection, yield prediction, credit scoring, market intelligence, and a farmer advisory chatbot. We need a Director of Data & AI to take these from prototype to production-grade systems that serve millions of farmers with actionable intelligence.\n\nResponsibilities:\n\u2022 Build and deploy credit scoring models using alternative data (satellite, mobile money, farm data)\n\u2022 Scale the AI crop doctor from prototype to production (disease detection, pest identification)\n\u2022 Develop yield prediction models using satellite imagery and weather data\n\u2022 Build market intelligence systems for commodity pricing and demand forecasting\n\u2022 Design and train the multilingual farmer advisory AI chatbot\n\u2022 Implement satellite-based crop monitoring and farm verification systems\n\u2022 Build weather data pipelines for parametric insurance triggers\n\u2022 Create data infrastructure for real-time analytics across 10 countries\n\u2022 Develop carbon credit measurement and verification algorithms\n\u2022 Ensure data privacy and sovereignty compliance across all jurisdictions',
  requirements = E'Requirements:\n\u2022 7+ years in data science/ML, with 3+ years leading teams\n\u2022 Strong experience with computer vision (crop/disease detection from imagery)\n\u2022 Experience building credit scoring or risk models for underbanked populations\n\u2022 Proficiency in Python, TensorFlow/PyTorch, and cloud ML platforms\n\u2022 Experience with geospatial data, satellite imagery (Sentinel, Planet Labs)\n\u2022 Understanding of agricultural data and farming systems\n\u2022 Experience deploying ML models at scale in production\n\nNice to Have:\n\u2022 Experience with Google Gemini API or similar LLM integration\n\u2022 Knowledge of blockchain data and on-chain analytics\n\u2022 Experience with weather data APIs and climate modelling\n\u2022 Remote sensing or precision agriculture background\n\u2022 PhD in relevant field (ML, statistics, agricultural science)',
  skills = ARRAY['Machine learning', 'Computer vision', 'Credit scoring', 'Satellite imagery', 'Python', 'NLP'],
  experience_years = 7,
  education = E'MSc/PhD in Data Science, ML, or related field'
WHERE title = 'Director of Data & AI';

-- 9. Director of Blockchain (position 25)
UPDATE job_listings SET
  created_at = '2026-03-25T00:25:00Z',
  description = E'AFU is building EDMA \u2014 a blockchain layer on Polygon for agricultural asset tokenization, stablecoin payments (AFUSD), carbon credit trading, and supply chain traceability. We need a Director of Blockchain to take this from concept to live infrastructure.\n\nResponsibilities:\n\u2022 Design and deploy the EDMA blockchain platform on Polygon\n\u2022 Build the AFUSD stablecoin (pegged to agricultural commodity basket)\n\u2022 Implement Real World Asset (RWA) tokenization for farm assets, equipment, and receivables\n\u2022 Build carbon credit measurement, verification, and trading infrastructure\n\u2022 Design smart contracts for automated insurance payouts and trade finance\n\u2022 Implement supply chain traceability from farm to fork\n\u2022 Ensure regulatory compliance for token issuance across all jurisdictions\n\u2022 Build wallet infrastructure that works for farmers (simplified UX)\n\u2022 Integrate blockchain layer with existing platform (Next.js, Supabase)\n\u2022 Design tokenomics and governance models',
  requirements = E'Requirements:\n\u2022 5+ years in blockchain development, with production deployments\n\u2022 Expert in Solidity, Polygon/Ethereum, and smart contract security\n\u2022 Experience with token issuance, stablecoins, or RWA tokenization\n\u2022 Understanding of DeFi protocols and decentralized governance\n\u2022 Knowledge of carbon credit markets and verification standards\n\u2022 Experience with supply chain traceability on blockchain\n\u2022 Understanding of regulatory landscape for digital assets in Africa\n\nNice to Have:\n\u2022 Experience with agricultural supply chain or commodity tokenization\n\u2022 Knowledge of MiCA, FATF, or African digital asset regulations\n\u2022 Experience building consumer-facing blockchain products (simplified UX)\n\u2022 Understanding of cross-border payment systems',
  skills = ARRAY['Solidity', 'Polygon/Ethereum', 'Smart contracts', 'RWA tokenization', 'DeFi', 'Supply chain traceability'],
  experience_years = 5,
  education = E'Computer Science or related field'
WHERE title = 'Director of Blockchain';

-- 10. Director of InfoSec (position 24)
UPDATE job_listings SET
  created_at = '2026-03-25T00:24:00Z',
  description = E'AFU handles sensitive financial data, farmer PII, and processes financial transactions across 10 countries. We need a Director of InfoSec to build a security program that protects our platform, our farmers, and our reputation from day one.\n\nResponsibilities:\n\u2022 Build and manage the information security program across all systems\n\u2022 Conduct regular penetration testing and vulnerability assessments\n\u2022 Implement and maintain SOC 2 Type II and ISO 27001 compliance\n\u2022 Ensure GDPR, POPIA, and local data protection compliance across 10 countries\n\u2022 Design and implement fraud detection systems for lending and payments\n\u2022 Manage incident response procedures and security monitoring\n\u2022 Oversee secure development practices and code security reviews\n\u2022 Ensure PCI-DSS compliance for payment processing\n\u2022 Build security awareness training for all staff\n\u2022 Manage third-party security assessments and vendor risk',
  requirements = E'Requirements:\n\u2022 7+ years in information security, with 3+ years in leadership\n\u2022 CISSP, CISM, or equivalent certification\n\u2022 Experience with financial services security requirements\n\u2022 Strong understanding of cloud security (Vercel, Supabase, AWS)\n\u2022 Experience with penetration testing and vulnerability management\n\u2022 Knowledge of African data protection regulations\n\u2022 Experience building security programs from scratch\n\nNice to Have:\n\u2022 Experience with fintech or payment platform security\n\u2022 Knowledge of blockchain security and smart contract auditing\n\u2022 Experience with mobile money security\n\u2022 SOC 2 and ISO 27001 implementation experience',
  skills = ARRAY['SOC 2', 'ISO 27001', 'PCI-DSS', 'Penetration testing', 'Security architecture', 'Cloud security'],
  experience_years = 7,
  education = E'Computer Science, Cybersecurity, or related field. CISSP/CISM certification'
WHERE title = 'Director of InfoSec';

-- 11. VP Operations (position 23)
UPDATE job_listings SET
  created_at = '2026-03-25T00:23:00Z',
  description = E'AFU operates across 10 African countries with farming operations, lending, insurance, trade finance, and supply chain logistics all running simultaneously. We need a VP Operations who can build the operational machine that makes all of this work at scale. You\u2019ll be Devon\u2019s right hand on the operations side.\n\nResponsibilities:\n\u2022 Build and manage cross-country operational processes and SLAs\n\u2022 Oversee country operations managers and ensure consistent quality across all markets\n\u2022 Design and optimize farmer onboarding, lending, and insurance workflows\n\u2022 Manage supply chain operations: inputs, equipment, processing, logistics\n\u2022 Build operational dashboards and KPI tracking across all countries\n\u2022 Coordinate with technology team on process automation and system improvements\n\u2022 Manage vendor and supplier relationships across all markets\n\u2022 Establish quality control and audit processes for field operations\n\u2022 Scale operations from 2 countries to 10 within 36 months\n\u2022 Build the operations team across all country offices',
  requirements = E'Requirements:\n\u2022 10+ years in operations management, with 5+ years in senior leadership\n\u2022 Experience in African agricultural operations or microfinance\n\u2022 Track record of scaling operations across multiple countries\n\u2022 Strong process design and optimization skills\n\u2022 Experience managing distributed teams across cultures and languages\n\u2022 Understanding of agricultural supply chains in Africa\n\u2022 Data-driven approach to operational decisions\n\nNice to Have:\n\u2022 Experience with cooperative operations or farmer organizations\n\u2022 Knowledge of mobile money operations and agent networks\n\u2022 Experience with warehouse receipt systems or commodity storage\n\u2022 Background in logistics or cold chain management',
  skills = ARRAY['Operations management', 'Multi-country scaling', 'Supply chain', 'Process design', 'Agricultural operations'],
  experience_years = 10,
  education = E'Business, Engineering, or related degree'
WHERE title = 'VP Operations';

-- 12. Director of Supply Chain (position 22)
UPDATE job_listings SET
  created_at = '2026-03-25T00:22:00Z',
  description = E'AFU procures farming inputs (seeds, fertilizer, chemicals), equipment (tractors, drones, irrigation), and manages post-harvest logistics (storage, processing, cold chain, transport) across 10 countries. We need someone who can build supplier networks, negotiate bulk pricing, and ensure the right inputs reach the right farmers at the right time.\n\nResponsibilities:\n\u2022 Build and manage supplier networks for farming inputs across 10 countries\n\u2022 Negotiate bulk procurement agreements for seeds, fertilizer, and agrochemicals\n\u2022 Manage equipment procurement and financing (tractors, drones, irrigation systems)\n\u2022 Design and operate post-harvest logistics: collection, grading, storage, transport\n\u2022 Build cold chain infrastructure for perishable exports (blueberries, fresh produce)\n\u2022 Implement warehouse receipt systems for commodity storage and financing\n\u2022 Manage last-mile delivery of inputs to smallholder farmers\n\u2022 Establish quality control standards for all inputs and commodities\n\u2022 Build inventory management and demand forecasting systems\n\u2022 Coordinate with trade finance team on export logistics documentation',
  requirements = E'Requirements:\n\u2022 7+ years in supply chain management, preferably in African agriculture\n\u2022 Experience with agricultural input distribution in frontier markets\n\u2022 Knowledge of cold chain logistics and perishable goods handling\n\u2022 Understanding of warehouse receipt systems and commodity storage\n\u2022 Strong negotiation skills and supplier management experience\n\u2022 Experience with last-mile delivery in rural African contexts\n\u2022 Understanding of import/export documentation and customs\n\nNice to Have:\n\u2022 Experience with agricultural equipment financing or leasing\n\u2022 Knowledge of drone technology for agricultural application\n\u2022 Experience with irrigation system procurement and installation\n\u2022 Understanding of organic or specialty crop supply chains',
  skills = ARRAY['Supply chain management', 'Cold chain logistics', 'Warehouse receipts', 'Procurement', 'Last-mile delivery'],
  experience_years = 7,
  education = E'Supply Chain, Business, or related degree'
WHERE title = 'Director of Supply Chain';

-- 13. Director of Farmer Success (position 21)
UPDATE job_listings SET
  created_at = '2026-03-25T00:21:00Z',
  description = E'Our farmers are our members, our customers, and our co-owners. We need someone who obsesses over their success. You\u2019ll design the onboarding experience, training programs, tier progression system, and support operations that take a farmer from signing up to thriving.\n\nResponsibilities:\n\u2022 Design and manage the farmer onboarding journey across all countries\n\u2022 Build and deliver training programs (in-person and digital) for the Seedling\u2192Pioneer progression\n\u2022 Establish farmer support operations: call center, WhatsApp, field support, chatbot training\n\u2022 Track farmer outcomes: yield improvement, income growth, loan repayment, satisfaction\n\u2022 Manage the farmer NPS program and continuous feedback loops\n\u2022 Design certification programs aligned with export market requirements\n\u2022 Coordinate with ambassador network on farmer recruitment and community engagement\n\u2022 Build farmer success metrics and reporting dashboards\n\u2022 Manage the progressive feature unlock system based on training completion\n\u2022 Create multilingual training content (video, audio, illustrated guides for low-literacy users)',
  requirements = E'Requirements:\n\u2022 5+ years in farmer extension, agricultural training, or customer success\n\u2022 Deep understanding of smallholder farmer challenges in Africa\n\u2022 Experience designing and delivering training programs for low-literacy audiences\n\u2022 Strong empathy and communication skills across cultures\n\u2022 Experience with agricultural extension services or farmer organizations\n\u2022 Understanding of adult learning principles in developing contexts\n\u2022 Willingness to spend significant time in the field with farmers\n\nNice to Have:\n\u2022 Experience with digital farmer training platforms\n\u2022 Knowledge of GlobalGAP, organic, or export certification programs\n\u2022 Fluency in an African language (Shona, Swahili, Luganda)\n\u2022 Background in community development or cooperative management',
  skills = ARRAY['Farmer training', 'Customer success', 'Program design', 'Impact measurement', 'Extension services'],
  experience_years = 5,
  education = E'Agriculture, Education, or related degree'
WHERE title = 'Director of Farmer Success';

-- 14. VP Business Development (position 20)
UPDATE job_listings SET
  created_at = '2026-03-25T00:20:00Z',
  description = E'AFU is expanding to 10 countries and needs someone who can open doors: government MOUs, DFI partnerships, institutional investor relationships, and strategic alliances. You\u2019ll be Peter\u2019s force multiplier on the commercial side.\n\nResponsibilities:\n\u2022 Lead market entry strategy for new countries \u2014 regulatory mapping, partnership identification, pilot design\n\u2022 Negotiate government MOUs and concessions for agricultural development programs\n\u2022 Build and manage DFI relationships (IFC, AfDB, CDC, FMO, USAID, AGRA)\n\u2022 Develop institutional investor pipeline and support fundraising efforts\n\u2022 Identify and negotiate strategic partnerships (banks, telcos, input companies, processors)\n\u2022 Lead partnership negotiations with Lloyd\u2019s syndicates and insurance partners\n\u2022 Build relationships with agricultural commodity exchanges\n\u2022 Develop public-private partnership proposals for agricultural infrastructure\n\u2022 Represent AFU at industry conferences, government forums, and investor events\n\u2022 Manage the business development team and pipeline CRM',
  requirements = E'Requirements:\n\u2022 10+ years in business development, with 5+ years in Africa\n\u2022 Strong existing network in African government, DFI, and institutional investor circles\n\u2022 Experience in agricultural development, fintech, or impact investment\n\u2022 Track record of closing large partnerships or deals ($10M+)\n\u2022 Understanding of African regulatory environments for financial services\n\u2022 Excellent presentation and negotiation skills\n\u2022 Willingness to travel 50%+ of the time across Africa\n\nNice to Have:\n\u2022 Existing relationships with DFIs (IFC, AfDB, CDC)\n\u2022 Experience with agricultural PPPs (public-private partnerships)\n\u2022 Government advisory experience in African countries\n\u2022 Knowledge of COMESA, SADC, or EAC trade frameworks',
  skills = ARRAY['Partnership development', 'DFI relationships', 'Government affairs', 'Market entry', 'Fundraising'],
  experience_years = 10,
  education = E'Business, International Relations, or related degree'
WHERE title = 'VP Business Development';

-- 15. Director of Trade Finance (position 19)
UPDATE job_listings SET
  created_at = '2026-03-25T00:19:00Z',
  description = E'AFU provides trade finance services to enable agricultural exports from Africa: SBLCs, Letters of Credit, export pre-financing, and FX services via Hamilton Reserve Bank. We need a Director of Trade Finance who can build and run this operation.\n\nResponsibilities:\n\u2022 Manage the SBLC origination and processing pipeline\n\u2022 Process Letters of Credit for agricultural commodity exports\n\u2022 Coordinate with Hamilton Reserve Bank on trade finance facilities\n\u2022 Manage FX operations and hedging for multi-currency agricultural trade\n\u2022 Build export pre-financing programs for commercial farmers\n\u2022 Design warehouse receipt financing products\n\u2022 Ensure compliance with international trade finance regulations\n\u2022 Manage documentary collections and bills of lading\n\u2022 Build trade finance reporting and portfolio monitoring systems\n\u2022 Train country teams on trade finance documentation requirements',
  requirements = E'Requirements:\n\u2022 7+ years in trade finance, with experience in commodity trade\n\u2022 Deep understanding of SBLCs, Letters of Credit, and documentary collections\n\u2022 Experience with African agricultural exports\n\u2022 Knowledge of international trade regulations (UCP 600, ISBP)\n\u2022 Experience managing banking relationships for trade finance\n\u2022 Strong attention to detail for documentation compliance\n\u2022 Understanding of FX risk management and hedging\n\nNice to Have:\n\u2022 Experience with Hamilton Reserve Bank or similar offshore banks\n\u2022 Knowledge of warehouse receipt finance systems\n\u2022 Experience with commodity exchange delivery and settlement\n\u2022 Understanding of agricultural commodity grading and certification',
  skills = ARRAY['Letters of Credit', 'SBLC', 'FX operations', 'Export finance', 'Commodity trade', 'Documentary collections'],
  experience_years = 7,
  education = E'Finance, Economics, or related degree. CDCS certification preferred'
WHERE title = 'Director of Trade Finance';

-- 16. Senior Commodity Trader (position 18)
UPDATE job_listings SET
  created_at = '2026-03-25T00:18:00Z',
  description = E'AFU is building a commodity trade desk that matches African agricultural production with global buyers. We need an experienced commodity trader who has sat on a trading desk, managed physical positions, hedged risk, and closed multi-million dollar deals. You will trade soft commodities (grains, oilseeds, horticulture, specialty crops) originating from our 10 African countries into domestic, regional, and international markets. This is hands-on trading \u2014 not strategy or advisory.\n\nResponsibilities:\n\u2022 Trade physical agricultural commodities originating from AFU\u2019s 10-country farmer network\n\u2022 Manage trading positions in maize, soya, blueberries, macadamia, cashew, cocoa, coffee, and specialty crops\n\u2022 Execute spot and forward contracts with domestic and international buyers\n\u2022 Hedge price risk using appropriate instruments (futures, options, swaps)\n\u2022 Build and manage the counterparty network: traders, processors, exporters, commodity houses\n\u2022 Negotiate offtake agreements with guaranteed minimum pricing for farmers\n\u2022 Monitor global commodity markets and identify arbitrage opportunities across AFU countries\n\u2022 Manage trade execution: pricing, contracts, logistics coordination, quality verification, payment\n\u2022 Coordinate with trade finance team on LC/SBLC requirements for each deal\n\u2022 Manage FX exposure on cross-border trades\n\u2022 Build market intelligence reports for the commercial team and farmer advisory\n\u2022 Develop new trade routes and buyer relationships in Europe, Middle East, and Asia\n\u2022 Manage counterparty credit risk and ensure proper documentation on all trades\n\u2022 Work with the blockchain team on commodity tokenization and traceability',
  requirements = E'Requirements:\n\u2022 7+ years as a commodity trader with a physical trading house, commodity merchant, or agri-trading firm\n\u2022 Proven P&L track record trading soft commodities (grains, oilseeds, coffee, cocoa, or horticulture)\n\u2022 Deep understanding of physical commodity logistics: shipping, warehousing, grading, certification\n\u2022 Experience with trade finance instruments: Letters of Credit, documentary collections, pre-export finance\n\u2022 Strong network of commodity buyers in at least 2 of: Europe, Middle East, Asia\n\u2022 Understanding of commodity hedging using futures and options (SAFEX, CME, ICE)\n\u2022 Experience with African agricultural commodities and origin markets\n\u2022 Ability to manage multiple positions and trades simultaneously\n\u2022 Strong analytical skills: market analysis, P&L management, risk assessment\n\u2022 Willingness to travel extensively to origin countries and buyer markets\n\nNice to Have:\n\u2022 Experience at a major trading house (Cargill, ADM, Louis Dreyfus, Olam, ETG, Export Trading Group)\n\u2022 SAFEX or JSE trading certification\n\u2022 Experience trading blueberries, macadamia, or high-value horticultural products\n\u2022 Knowledge of fair trade, organic, or Rainforest Alliance certified supply chains\n\u2022 Experience with commodity exchange warehouse delivery mechanisms\n\u2022 Understanding of carbon credit markets and agricultural carbon trading\n\u2022 Network in East or Southern African commodity markets specifically',
  skills = ARRAY['Commodity trading', 'Risk hedging', 'Forward contracts', 'Market analysis', 'P&L management', 'Trade execution'],
  experience_years = 7,
  education = E'Finance, Economics, Agriculture, or related field'
WHERE title = 'Senior Commodity Trader';

-- ============================================================================
-- TIER 3 — REGIONAL DIRECTORS (positions 17–15)
-- ============================================================================

-- 17. Regional Director — Southern Africa (position 17)
UPDATE job_listings SET
  created_at = '2026-03-25T00:17:00Z',
  description = E'You will oversee AFU operations across Zimbabwe, Botswana, Mozambique, and Zambia. This is the pilot region \u2014 Zimbabwe launches first with the Watson & Fine blueberry project and 19,000 smallholder farmers. You need to make the model work here before we scale it continent-wide.\n\nResponsibilities:\n\u2022 Oversee 4 Country Directors and their teams across Southern Africa\n\u2022 Own the regional P&L and growth targets\n\u2022 Ensure the Zimbabwe pilot succeeds as the template for all other countries\n\u2022 Manage cross-border logistics and trade between Southern African countries\n\u2022 Build regional government and institutional relationships\n\u2022 Coordinate regional supply chain and procurement for cost efficiencies\n\u2022 Manage regional risk and compliance across all 4 jurisdictions\n\u2022 Report to HQ on regional performance, challenges, and opportunities\n\u2022 Build the regional team and establish the Harare regional office\n\u2022 Represent AFU at SADC and COMESA forums',
  requirements = E'Requirements:\n\u2022 10+ years in senior management in Southern Africa\n\u2022 Deep understanding of Zimbabwean agricultural sector\n\u2022 Experience managing teams across multiple countries\n\u2022 Strong government and institutional relationships in the region\n\u2022 Understanding of agricultural finance, insurance, or commodity trade\n\u2022 Track record of building and scaling operations\n\u2022 Knowledge of SADC trade frameworks and regulations\n\nNice to Have:\n\u2022 Experience in agricultural commodity exports from Zimbabwe\n\u2022 Knowledge of blueberry or horticultural operations\n\u2022 Existing relationships with Zimbabwean government agriculture ministry\n\u2022 Understanding of cooperative structures in Southern Africa',
  skills = ARRAY['Regional leadership', 'P&L management', 'SADC trade', 'Agricultural development'],
  experience_years = 10,
  education = E'Business, Agriculture, or related degree'
WHERE title = 'Regional Director — Southern Africa';

-- 18. Regional Director — East Africa (position 16)
UPDATE job_listings SET
  created_at = '2026-03-25T00:16:00Z',
  description = E'East Africa is AFU\u2019s growth engine: Uganda launches with 19,000 pre-identified farmers, Kenya is the fintech hub, and Tanzania offers massive agricultural potential. You\u2019ll build and scale operations across all three markets.\n\nResponsibilities:\n\u2022 Oversee 3 Country Directors and their teams across East Africa\n\u2022 Own the regional P&L and growth targets\n\u2022 Launch Uganda operations with 19,000 farmer onboarding\n\u2022 Leverage Kenya\u2019s fintech ecosystem for mobile money and payment innovation\n\u2022 Build regional partnerships with M-Pesa, Safaricom, and East African banks\n\u2022 Manage cross-border trade within the EAC (East African Community)\n\u2022 Coordinate with Nairobi-based commodity exchanges and export infrastructure\n\u2022 Build the regional team and establish the Nairobi regional office\n\u2022 Represent AFU at EAC forums and regional agricultural conferences\n\u2022 Scale operations to serve 100,000+ farmers across the region within 3 years',
  requirements = E'Requirements:\n\u2022 10+ years in senior management in East Africa\n\u2022 Deep understanding of agricultural operations in Uganda, Kenya, and/or Tanzania\n\u2022 Experience with mobile money ecosystems (M-Pesa, MTN MoMo, Airtel Money)\n\u2022 Strong network in East African business, government, and development circles\n\u2022 Track record of scaling operations in multiple East African countries\n\u2022 Understanding of EAC trade frameworks\n\nNice to Have:\n\u2022 Experience with agricultural cooperatives or farmer organizations in East Africa\n\u2022 Knowledge of Ugandan agricultural sector specifically\n\u2022 Existing relationships with DFIs operating in East Africa\n\u2022 Experience with coffee, tea, or horticultural exports',
  skills = ARRAY['Regional leadership', 'Mobile money', 'EAC markets', 'Farmer networks'],
  experience_years = 10,
  education = E'Business, Agriculture, or related degree'
WHERE title = 'Regional Director — East Africa';

-- 19. Regional Director — West Africa (position 15)
UPDATE job_listings SET
  created_at = '2026-03-25T00:15:00Z',
  description = E'West Africa represents AFU\u2019s largest total addressable market: Nigeria alone has 40M+ smallholder farmers. Ghana and Senegal offer stable regulatory environments for pilot entry. You\u2019ll build the playbook for West African expansion.\n\nResponsibilities:\n\u2022 Oversee 3 Country Directors across Ghana, Nigeria, and Senegal\n\u2022 Own the regional P&L and growth targets\n\u2022 Navigate the complex Nigerian regulatory environment for fintech and agriculture\n\u2022 Build partnerships with West African banks, mobile money operators, and agri-businesses\n\u2022 Manage francophone operations in Senegal (French-speaking market entry)\n\u2022 Coordinate with ECOWAS trade frameworks for cross-border agricultural trade\n\u2022 Build the regional team and establish the Accra regional office\n\u2022 Develop cocoa, cashew, and staple crop value chains in the region\n\u2022 Represent AFU at ECOWAS and West African agricultural forums\n\u2022 Scale to serve 200,000+ farmers across West Africa within 4 years',
  requirements = E'Requirements:\n\u2022 10+ years in senior management in West Africa\n\u2022 Experience across both anglophone (Ghana, Nigeria) and francophone (Senegal) markets\n\u2022 Understanding of agricultural value chains in West Africa (cocoa, cashew, rice, cassava)\n\u2022 Strong network in West African business and government circles\n\u2022 Experience navigating Nigerian regulatory complexity\n\u2022 Fluency in English and French\n\nNice to Have:\n\u2022 Experience with Orange Money, MTN MoMo, or other West African mobile money\n\u2022 Knowledge of ECOWAS trade regulations\n\u2022 Existing relationships with West African DFIs or development organizations\n\u2022 Experience with cocoa or cashew export operations',
  skills = ARRAY['Regional leadership', 'Francophone markets', 'Cocoa/cashew value chains', 'ECOWAS trade'],
  experience_years = 10,
  education = E'Business, Agriculture, or related degree'
WHERE title = 'Regional Director — West Africa';

-- ============================================================================
-- TIER 4 — COUNTRY DIRECTORS (positions 14–13)
-- ============================================================================

-- 20. Country Director — Zimbabwe (Pilot) (position 14)
UPDATE job_listings SET
  created_at = '2026-03-25T00:14:00Z',
  description = E'Zimbabwe is AFU\u2019s pilot country. Everything we build here becomes the template for 9 more countries. You\u2019ll launch the Watson & Fine blueberry export program, onboard the first cohort of smallholder farmers, and prove that the AFU model works. This is the most important Country Director role in the company.\n\nResponsibilities:\n\u2022 Own the Zimbabwe P&L \u2014 revenue, costs, farmer growth, loan performance\n\u2022 Launch the Watson & Fine blueberry export program (25ha commercial operation)\n\u2022 Onboard the first 5,000 smallholder farmers in Year 1\n\u2022 Build and manage the Zimbabwe team (Operations, Finance, Agronomy, Commercial, Insurance, Compliance)\n\u2022 Establish relationships with Zimbabwean government (Agriculture Ministry, RBZ, ZIMRA)\n\u2022 Register and operationalize the Zimbabwe farmer cooperative (51% farmer-owned)\n\u2022 Manage local banking relationships and EcoCash mobile money integration\n\u2022 Ensure all operations comply with Zimbabwean regulations\n\u2022 Coordinate with HQ on platform localization (Shona language, local content)\n\u2022 Build the proof-of-concept that unlocks the next $450M+ in deployment',
  requirements = E'Requirements:\n\u2022 7+ years in agricultural business, development, or fintech in Zimbabwe\n\u2022 Deep understanding of Zimbabwean farming landscape (commercial and smallholder)\n\u2022 Strong relationships with Zimbabwean government and agricultural institutions\n\u2022 Experience managing teams of 20+ people\n\u2022 Understanding of EcoCash and local payment systems\n\u2022 Knowledge of Zimbabwean cooperative and agricultural law\n\u2022 Track record of delivering results in challenging environments\n\u2022 Fluency in English and Shona\n\nNice to Have:\n\u2022 Experience with blueberry or horticultural operations\n\u2022 Knowledge of tobacco, maize, or soya value chains in Zimbabwe\n\u2022 Existing relationships with TIMB, GMB, or other statutory bodies\n\u2022 Experience with agricultural lending or microfinance in Zimbabwe',
  skills = ARRAY['Country leadership', 'Cooperative management', 'Agricultural development', 'Regulatory affairs'],
  experience_years = 7,
  education = E'Business, Agriculture, or related degree'
WHERE title = 'Country Director — Zimbabwe (Pilot)';

-- 21. Country Director — Uganda (position 13)
UPDATE job_listings SET
  created_at = '2026-03-25T00:13:00Z',
  description = E'Launch Uganda operations with 19,000 pre-identified farmers. Build the team, register the cooperative, establish MTN MoMo/Airtel Money operations, and scale coffee, maize, and banana value chains. Uganda is AFU\u2019s second market and a critical proof point for East African expansion.\n\nResponsibilities:\n\u2022 Own the Uganda P&L \u2014 revenue, costs, farmer growth, loan performance\n\u2022 Onboard 19,000 pre-identified farmers in Year 1\n\u2022 Register and operationalize the Uganda farmer cooperative (51% farmer-owned)\n\u2022 Establish MTN MoMo and Airtel Money integration for loan disbursements and collections\n\u2022 Build and manage the Uganda country team (Operations, Finance, Agronomy, Commercial)\n\u2022 Develop coffee, maize, and banana value chains with local and export buyers\n\u2022 Build relationships with Ugandan government (MAAIF, Bank of Uganda, URA)\n\u2022 Coordinate with Regional Director \u2014 East Africa on cross-border trade opportunities\n\u2022 Ensure all operations comply with Ugandan regulations and cooperative law\n\u2022 Coordinate with HQ on platform localization (Luganda language, local content)',
  requirements = E'Requirements:\n\u2022 7+ years in agricultural business, development, or fintech in Uganda\n\u2022 Deep understanding of Ugandan farming landscape (smallholder and commercial)\n\u2022 Strong relationships with Ugandan government and agricultural institutions\n\u2022 Experience managing teams of 15+ people\n\u2022 Understanding of MTN MoMo, Airtel Money, and local payment systems\n\u2022 Knowledge of Ugandan cooperative and agricultural law\n\u2022 Track record of delivering results in East African markets\n\u2022 Fluency in English and Luganda\n\nNice to Have:\n\u2022 Experience with coffee, maize, or banana value chains in Uganda\n\u2022 Existing relationships with UCDA, NAADS, or other agricultural bodies\n\u2022 Experience with agricultural lending or microfinance in Uganda\n\u2022 Knowledge of EAC cross-border trade frameworks',
  skills = ARRAY['Country operations', 'Cooperative formation', 'Mobile money', 'Coffee/maize value chains'],
  experience_years = 7,
  education = E'Business, Agriculture, or related degree'
WHERE title = 'Country Director — Uganda';

-- ============================================================================
-- TIER 5 — COUNTRY MANAGEMENT (positions 12–6)
-- ============================================================================

-- 22. Country Operations Manager (position 12)
UPDATE job_listings SET
  created_at = '2026-03-25T00:12:00Z',
  description = E'You are the engine that makes a country run. You manage farmer onboarding, daily operations, logistics, field teams, and everything in between. While the Country Director handles strategy and relationships, you handle execution.\n\nResponsibilities:\n\u2022 Manage day-to-day operations: farmer onboarding, input distribution, crop collection\n\u2022 Supervise field agronomists, loan officers, warehouse managers, and extension workers\n\u2022 Coordinate logistics: input delivery schedules, crop collection routes, storage allocation\n\u2022 Manage farmer training program delivery in the field\n\u2022 Handle escalated farmer issues and resolve operational bottlenecks\n\u2022 Track and report on operational KPIs (farmers onboarded, loans disbursed, crops collected)\n\u2022 Ensure quality standards for inputs distributed and crops collected\n\u2022 Manage vendor relationships for local services (transport, storage, processing)\n\u2022 Coordinate with HQ technology team on system issues and feature requests\n\u2022 Build and maintain the local team culture and morale',
  requirements = E'Requirements:\n\u2022 5+ years in operations management, preferably in agriculture or microfinance\n\u2022 Experience managing field teams in rural African environments\n\u2022 Strong organizational and logistics skills\n\u2022 Problem-solving ability in resource-constrained environments\n\u2022 Understanding of agricultural cycles and farmer needs\n\u2022 Proficiency with technology and mobile applications\n\u2022 Fluency in local language(s) plus English\n\nNice to Have:\n\u2022 Experience with agricultural cooperative operations\n\u2022 Knowledge of warehouse management and commodity storage\n\u2022 Experience with mobile money operations\n\u2022 Background in agricultural extension',
  skills = ARRAY['Operations management', 'Logistics', 'Team supervision', 'Agricultural operations', 'KPI tracking'],
  experience_years = 5,
  education = E'Business, Agriculture, or related degree'
WHERE title = 'Country Operations Manager';

-- 23. Country Finance Manager (position 11)
UPDATE job_listings SET
  created_at = '2026-03-25T00:11:00Z',
  description = E'You manage the money at the country level: loan disbursements, collections, mobile money operations, and financial reporting. You\u2019re the person who ensures farmers get funded on time and repayments flow back smoothly.\n\nResponsibilities:\n\u2022 Manage loan origination and disbursement processes\n\u2022 Oversee loan collections and manage portfolio quality (PAR30, write-offs)\n\u2022 Operate mobile money disbursement and collection channels\n\u2022 Process insurance premium collections and claims payouts\n\u2022 Prepare monthly financial reports for country and HQ\n\u2022 Manage local bank accounts and cash flow\n\u2022 Verify farmer KYC documentation and credit references\n\u2022 Coordinate with field loan officers on credit assessments\n\u2022 Manage cooperative financial records and farmer dividend calculations\n\u2022 Ensure compliance with local financial regulations',
  requirements = E'Requirements:\n\u2022 5+ years in microfinance, agricultural lending, or banking in Africa\n\u2022 Experience with loan portfolio management and collections\n\u2022 Understanding of mobile money operations and float management\n\u2022 Strong financial reporting and analytical skills\n\u2022 Knowledge of local financial regulations and KYC requirements\n\u2022 Experience with credit assessment for agricultural borrowers\n\u2022 Professional accounting qualification (CPA, ACCA, or equivalent)\n\nNice to Have:\n\u2022 Experience with cooperative financial management\n\u2022 Knowledge of agricultural insurance operations\n\u2022 Experience with digital lending platforms\n\u2022 Understanding of warehouse receipt financing',
  skills = ARRAY['Loan management', 'Mobile money', 'Financial reporting', 'Portfolio quality', 'KYC/AML'],
  experience_years = 5,
  education = E'Finance, Accounting, or related degree. CPA/ACCA qualification'
WHERE title = 'Country Finance Manager';

-- 24. Country Agronomist Lead (position 10)
UPDATE job_listings SET
  created_at = '2026-03-25T00:10:00Z',
  description = E'You are the agricultural brain of the country operation. You assess farms, advise farmers, train extension workers, and ensure crop quality meets export standards. Your work directly determines whether farmers succeed and whether AFU\u2019s lending is safe.\n\nResponsibilities:\n\u2022 Conduct farm assessments for new farmer onboarding and loan applications\n\u2022 Provide crop advisory services to farmers (planting, pest management, harvest timing)\n\u2022 Lead and train the field agronomist team\n\u2022 Monitor crop health and yield across the farmer portfolio using satellite and field data\n\u2022 Ensure compliance with export quality standards (GlobalGAP, HACCP, organic)\n\u2022 Design and deliver farmer training programs on best agricultural practices\n\u2022 Conduct soil testing and provide fertilizer recommendations\n\u2022 Support insurance teams with crop damage assessments\n\u2022 Manage demonstration plots and farmer field schools\n\u2022 Provide technical input for credit assessments and crop viability analysis',
  requirements = E'Requirements:\n\u2022 BSc/MSc in Agriculture, Agronomy, or related field\n\u2022 5+ years as a practicing agronomist in Africa\n\u2022 Deep knowledge of local crops, soils, and farming systems\n\u2022 Experience with farmer extension and training\n\u2022 Understanding of export crop quality requirements\n\u2022 Ability to train and manage field agronomist teams\n\u2022 Proficiency with agricultural data collection tools\n\u2022 Fluency in local language(s)\n\nNice to Have:\n\u2022 Experience with blueberry, macadamia, or high-value crop agronomy\n\u2022 Knowledge of precision agriculture tools (drones, satellite monitoring)\n\u2022 Experience with organic or conservation agriculture practices\n\u2022 Understanding of climate-smart agriculture',
  skills = ARRAY['Agronomy', 'Crop advisory', 'Farm assessment', 'Training delivery', 'Export quality standards'],
  experience_years = 5,
  education = E'BSc/MSc in Agriculture, Agronomy, or related field'
WHERE title = 'Country Agronomist Lead';

-- 25. Country Commercial Manager (position 9)
UPDATE job_listings SET
  created_at = '2026-03-25T00:09:00Z',
  description = E'You find the buyers, negotiate the prices, and make sure every farmer\u2019s harvest has a home. You\u2019re the link between production and market \u2014 the person who turns crops into cash.\n\nResponsibilities:\n\u2022 Build and manage local buyer relationships (wholesalers, processors, retailers, exporters)\n\u2022 Negotiate offtake agreements with guaranteed minimum prices for farmers\n\u2022 Monitor local commodity prices and market intelligence\n\u2022 Coordinate crop aggregation and delivery to buyers\n\u2022 Manage the AFU Fresh marketplace listings for the country\n\u2022 Identify new market opportunities and crop diversification options\n\u2022 Ensure quality standards meet buyer requirements\n\u2022 Coordinate with trade finance team on export documentation\n\u2022 Manage the country exchange/barter marketplace\n\u2022 Report on commercial performance (volumes, prices, margins, buyer satisfaction)',
  requirements = E'Requirements:\n\u2022 5+ years in agricultural marketing, commodity trading, or agri-business\n\u2022 Strong local network of agricultural buyers and processors\n\u2022 Understanding of commodity pricing and market dynamics\n\u2022 Experience negotiating supply contracts\n\u2022 Knowledge of agricultural grading and quality standards\n\u2022 Strong relationship management skills\n\u2022 Fluency in local language(s) and English\n\nNice to Have:\n\u2022 Experience with agricultural export logistics\n\u2022 Knowledge of fair trade or sustainability certifications\n\u2022 Experience with commodity exchange operations\n\u2022 Understanding of food processing requirements',
  skills = ARRAY['Agricultural marketing', 'Buyer relationships', 'Commodity pricing', 'Offtake negotiation', 'Market intelligence'],
  experience_years = 5,
  education = E'Business, Agriculture, or related degree'
WHERE title = 'Country Commercial Manager';

-- 26. Country Insurance Officer (position 8)
UPDATE job_listings SET
  created_at = '2026-03-25T00:08:00Z',
  description = E'You manage crop insurance operations at the country level: selling policies, processing claims, conducting farm assessments, and reporting to Lloyd\u2019s. You protect farmers from the risks that can wipe out a season\u2019s work.\n\nResponsibilities:\n\u2022 Manage crop insurance sales and farmer education on insurance products\n\u2022 Process insurance claims: receive, assess, verify, and recommend payouts\n\u2022 Conduct farm assessments for insurance underwriting\n\u2022 Monitor weather data and parametric triggers for index-based insurance\n\u2022 Coordinate with field agronomists on crop damage verification\n\u2022 Prepare Lloyd\u2019s coverholder reports and compliance documentation\n\u2022 Manage relationships with local insurance regulators\n\u2022 Train farmers and field staff on insurance processes\n\u2022 Track portfolio performance (claims ratio, premium collection, farmer satisfaction)\n\u2022 Identify and prevent fraudulent claims',
  requirements = E'Requirements:\n\u2022 3+ years in insurance, ideally agricultural or microinsurance\n\u2022 Understanding of crop insurance products (indemnity and parametric)\n\u2022 Knowledge of local insurance regulations\n\u2022 Experience with claims processing and assessment\n\u2022 Strong attention to detail and analytical skills\n\u2022 Ability to work in rural environments\n\u2022 Insurance qualification or diploma preferred\n\nNice to Have:\n\u2022 Experience with Lloyd\u2019s or international reinsurance\n\u2022 Knowledge of weather index insurance\n\u2022 Understanding of satellite-based crop monitoring\n\u2022 Actuarial or risk assessment background',
  skills = ARRAY['Crop insurance', 'Claims processing', 'Parametric insurance', 'Lloyd''s reporting', 'Farm assessment'],
  experience_years = 3,
  education = E'Insurance, Finance, or related field. Insurance qualification preferred'
WHERE title = 'Country Insurance Officer';

-- 27. Country Compliance Officer (position 7)
UPDATE job_listings SET
  created_at = '2026-03-25T00:07:00Z',
  description = E'You ensure AFU operates legally and ethically in your country. KYC/AML compliance, cooperative governance, regulatory filings, and data protection all fall on your shoulders.\n\nResponsibilities:\n\u2022 Manage KYC/AML compliance for all farmer and partner onboarding\n\u2022 Ensure cooperative governance compliance (board meetings, member records, annual filings)\n\u2022 File regulatory reports with financial services and cooperative regulators\n\u2022 Conduct compliance training for country staff\n\u2022 Monitor and report on regulatory changes that affect AFU operations\n\u2022 Manage data protection compliance (local data protection laws)\n\u2022 Oversee audit preparation and coordinate with external auditors\n\u2022 Maintain the country compliance manual and update procedures\n\u2022 Investigate and report compliance incidents or suspicious activity\n\u2022 Coordinate with HQ legal team on contracts and regulatory queries',
  requirements = E'Requirements:\n\u2022 3+ years in compliance, legal, or regulatory roles\n\u2022 Knowledge of local financial services and cooperative regulations\n\u2022 Understanding of KYC/AML requirements\n\u2022 Strong attention to detail and documentation skills\n\u2022 Experience with regulatory filings and audit processes\n\u2022 Legal qualification or compliance certification preferred\n\u2022 Fluency in local language(s) and English\n\nNice to Have:\n\u2022 Experience with microfinance or agricultural lending compliance\n\u2022 Knowledge of data protection regulations\n\u2022 Experience with cooperative law\n\u2022 Anti-money laundering certification',
  skills = ARRAY['KYC/AML', 'Regulatory compliance', 'Cooperative governance', 'Data protection', 'Audit coordination'],
  experience_years = 3,
  education = E'Law, Compliance, or related field'
WHERE title = 'Country Compliance Officer';

-- 28. Country Ambassador Coordinator (position 6)
UPDATE job_listings SET
  created_at = '2026-03-25T00:06:00Z',
  description = E'Ambassadors are the face of AFU in farming communities. You recruit, train, and manage a network of local ambassadors who sign up farmers, provide basic support, and build trust in communities where technology and formal finance are new concepts.\n\nResponsibilities:\n\u2022 Recruit and onboard ambassador network across the country\n\u2022 Train ambassadors on AFU products, platform usage, and farmer communication\n\u2022 Set and track ambassador performance targets (farmers recruited, active users, satisfaction)\n\u2022 Manage ambassador compensation (commissions, incentives, recognition programs)\n\u2022 Organize community events, farmer field days, and awareness campaigns\n\u2022 Collect farmer feedback through ambassador network and escalate to HQ\n\u2022 Coordinate with marketing team on promotional materials and campaigns\n\u2022 Manage the ambassador portal and communication channels\n\u2022 Resolve community concerns and build trust in AFU\u2019s services\n\u2022 Identify high-performing ambassadors for career progression within AFU',
  requirements = E'Requirements:\n\u2022 3+ years in community mobilization, agent network management, or field sales\n\u2022 Experience working in rural African communities\n\u2022 Strong interpersonal and leadership skills\n\u2022 Experience managing distributed teams or agent networks\n\u2022 Understanding of agricultural communities and farmer needs\n\u2022 Proficiency with mobile technology\n\u2022 Fluency in local language(s)\n\nNice to Have:\n\u2022 Experience with mobile money agent network management\n\u2022 Background in agricultural extension or NGO field operations\n\u2022 Experience with community health worker or similar agent models\n\u2022 Knowledge of adult literacy and basic training delivery',
  skills = ARRAY['Community mobilization', 'Agent network management', 'Training delivery', 'Field sales', 'Farmer engagement'],
  experience_years = 3,
  education = E'Community Development, Agriculture, or related field'
WHERE title = 'Country Ambassador Coordinator';

-- ============================================================================
-- TIER 6 — FIELD OPERATIONS (positions 5–3)
-- ============================================================================

-- 29. Field Agronomist (position 5)
UPDATE job_listings SET
  created_at = '2026-03-25T00:05:00Z',
  description = E'You are on the ground with farmers every day. You visit farms, test soil, advise on crops, monitor for disease, and deliver training. You are the direct link between AFU\u2019s technology platform and the farmer\u2019s field.\n\nResponsibilities:\n\u2022 Visit farmers regularly to assess crop health and provide advisory\n\u2022 Conduct soil testing and provide tailored fertilizer and input recommendations\n\u2022 Deliver farmer training sessions on best agricultural practices\n\u2022 Use the AFU mobile app to record farm data, photos, and GPS coordinates\n\u2022 Monitor for pest and disease outbreaks and recommend treatments\n\u2022 Support loan officers with farm assessments for credit decisions\n\u2022 Assist with crop damage assessments for insurance claims\n\u2022 Collect harvest data and coordinate with collection logistics\n\u2022 Serve as the technical expert for your assigned farmer portfolio\n\u2022 Report weekly on farm conditions, challenges, and training completed',
  requirements = E'Requirements:\n\u2022 Diploma or BSc in Agriculture, Crop Science, or related field\n\u2022 2+ years field experience in agricultural extension or agronomy\n\u2022 Knowledge of local crops, soils, pests, and farming practices\n\u2022 Comfortable using mobile applications for data collection\n\u2022 Motorcycle license (travel to rural farms required)\n\u2022 Physical fitness for field work in all weather conditions\n\u2022 Strong communication skills with farmers of all education levels\n\u2022 Fluency in local language(s)\n\nNice to Have:\n\u2022 Experience with precision agriculture tools\n\u2022 Knowledge of organic farming practices\n\u2022 First aid certification\n\u2022 Experience with agricultural data collection apps',
  skills = ARRAY['Crop advisory', 'Soil testing', 'Farmer training', 'Field data collection', 'Pest management'],
  experience_years = 2,
  education = E'Diploma or BSc in Agriculture, Crop Science, or related field'
WHERE title = 'Field Agronomist';

-- 30. Loan Officer (position 4)
UPDATE job_listings SET
  created_at = '2026-03-25T00:04:00Z',
  description = E'You assess farmers for creditworthiness, verify their references, monitor loan usage, and manage collections. In the African context, character references and community reputation matter as much as financials. You need to know your farmers.\n\nResponsibilities:\n\u2022 Conduct farmer credit assessments: farm visits, reference checks, financial history review\n\u2022 Verify character references \u2014 visit referees, assess farmer reputation in community\n\u2022 Process loan applications through the AFU platform\n\u2022 Monitor loan utilization: ensure funds are used for stated agricultural purposes\n\u2022 Manage loan collections and farmer repayment schedules\n\u2022 Conduct follow-up visits for overdue accounts\n\u2022 Coordinate with agronomists on crop viability for lending decisions\n\u2022 Build relationships with farming communities to identify creditworthy borrowers\n\u2022 Report on portfolio quality (disbursement, collection, PAR30, defaults)\n\u2022 Educate farmers on financial literacy and responsible borrowing',
  requirements = E'Requirements:\n\u2022 2+ years in microfinance, agricultural lending, or banking\n\u2022 Experience with credit assessment in rural African contexts\n\u2022 Understanding of agricultural cycles and cash flow timing\n\u2022 Strong interpersonal skills and community trust\n\u2022 Comfortable using mobile technology for data entry and reporting\n\u2022 Motorcycle license for rural travel\n\u2022 Integrity and strong ethical standards \u2014 this is non-negotiable\n\u2022 Fluency in local language(s)\n\nNice to Have:\n\u2022 Experience with mobile money lending platforms\n\u2022 Knowledge of cooperative lending models\n\u2022 Financial literacy training experience\n\u2022 Background in community development',
  skills = ARRAY['Credit assessment', 'Loan collections', 'Financial literacy', 'Community relations', 'Portfolio management'],
  experience_years = 2,
  education = E'Finance, Banking, or related field'
WHERE title = 'Loan Officer';

-- 31. Warehouse Manager (position 3)
UPDATE job_listings SET
  created_at = '2026-03-25T00:03:00Z',
  description = E'You manage the physical hub where crops come in, get graded, stored, and shipped out. Warehouse receipt finance means your inventory records are financial instruments \u2014 accuracy is everything.\n\nResponsibilities:\n\u2022 Manage receiving, grading, weighing, and storage of agricultural commodities\n\u2022 Maintain accurate inventory records for warehouse receipt financing\n\u2022 Ensure proper storage conditions (temperature, humidity, pest control)\n\u2022 Coordinate inbound deliveries from farmers and outbound shipments to buyers\n\u2022 Issue warehouse receipts and manage the receipt register\n\u2022 Maintain cold chain integrity for perishable commodities\n\u2022 Manage warehouse staff (laborers, graders, security)\n\u2022 Ensure food safety and quality standards compliance\n\u2022 Report daily on inventory levels, receipts, and dispatches\n\u2022 Coordinate with logistics team on transport scheduling',
  requirements = E'Requirements:\n\u2022 3+ years in warehouse management, preferably agricultural commodities\n\u2022 Experience with commodity grading and quality assessment\n\u2022 Understanding of warehouse receipt systems\n\u2022 Strong organizational and inventory management skills\n\u2022 Knowledge of food safety and storage requirements\n\u2022 Basic computer skills for inventory management systems\n\u2022 Physical fitness for warehouse environment\n\nNice to Have:\n\u2022 Experience with cold chain management\n\u2022 Knowledge of export packaging and documentation\n\u2022 Forklift certification\n\u2022 Experience with HACCP or food safety systems',
  skills = ARRAY['Warehouse management', 'Commodity grading', 'Inventory control', 'Cold chain', 'Warehouse receipts'],
  experience_years = 3,
  education = E'Supply Chain, Logistics, or related field'
WHERE title = 'Warehouse Manager';

-- ============================================================================
-- TIER 7 — CENTRAL HQ (positions 2–1)
-- ============================================================================

-- 32. Marketing & Communications Lead (position 2)
UPDATE job_listings SET
  created_at = '2026-03-25T00:02:00Z',
  description = E'AFU\u2019s story is powerful: by farmers, for farmers, the Amazon of African agriculture. We need someone who can tell this story to farmers, investors, governments, and the media in a way that builds trust and drives growth.\n\nResponsibilities:\n\u2022 Build and manage the AFU brand across all channels (digital, print, events, PR)\n\u2022 Create investor-facing materials: pitch decks, one-pagers, impact reports\n\u2022 Design farmer-facing marketing: multilingual campaigns, radio, SMS, WhatsApp, community events\n\u2022 Manage social media presence and content strategy\n\u2022 Build PR strategy and manage media relationships across Africa\n\u2022 Create content for the AFU website, blog, and newsletter\n\u2022 Design co-branded materials for partnerships (Lloyd\u2019s, Hamilton Reserve, government)\n\u2022 Manage the AFU ambassador marketing toolkit\n\u2022 Coordinate with product team on in-app messaging and farmer communications\n\u2022 Track marketing performance metrics and optimize spend',
  requirements = E'Requirements:\n\u2022 5+ years in marketing, preferably in agritech, fintech, or development sector\n\u2022 Experience with both B2C (farmer-facing) and B2B (investor/partner) marketing\n\u2022 Strong writing and storytelling skills\n\u2022 Experience with digital marketing in African markets\n\u2022 Understanding of multilingual campaign requirements\n\u2022 Design skills or experience managing design teams\n\u2022 Experience with impact reporting and ESG communications\n\nNice to Have:\n\u2022 Experience with farmer-facing marketing in Africa\n\u2022 Knowledge of radio and SMS marketing in rural contexts\n\u2022 Video production skills\n\u2022 Understanding of agricultural sector media landscape',
  skills = ARRAY['Brand management', 'Content strategy', 'Digital marketing', 'Multilingual campaigns', 'Investor communications'],
  experience_years = 5,
  education = E'Marketing, Communications, or related degree'
WHERE title = 'Marketing & Communications Lead';

-- 33. Customer Support Lead (position 1)
UPDATE job_listings SET
  created_at = '2026-03-25T00:01:00Z',
  description = E'Farmers will call, message, and WhatsApp us with questions about loans, insurance, inputs, crops, payments, and everything in between. You build and run the support operation that makes every farmer feel heard and helped.\n\nResponsibilities:\n\u2022 Build the customer support function from scratch: processes, tools, knowledge base\n\u2022 Manage multilingual support across phone, WhatsApp, in-app chat, and email\n\u2022 Train and manage the support team across multiple countries\n\u2022 Design support workflows for different query types (finance, insurance, agronomy, tech)\n\u2022 Monitor and improve response times, resolution rates, and farmer satisfaction\n\u2022 Build and maintain the farmer FAQ and self-service knowledge base\n\u2022 Coordinate with product team to improve the AI chatbot responses\n\u2022 Escalate system issues and bugs to the engineering team\n\u2022 Produce weekly support reports with trends and farmer feedback\n\u2022 Design and implement a farmer NPS tracking program',
  requirements = E'Requirements:\n\u2022 3+ years in customer support, preferably managing teams\n\u2022 Experience supporting users in African markets\n\u2022 Multilingual ability (at least 2 African languages plus English)\n\u2022 Experience with support tools (Zendesk, Intercom, or similar)\n\u2022 Strong empathy and communication skills\n\u2022 Experience building support processes from scratch\n\u2022 Comfort with technology and ability to troubleshoot platform issues\n\nNice to Have:\n\u2022 Experience with WhatsApp Business API for support\n\u2022 Background in agricultural extension or farmer education\n\u2022 Experience with chatbot training and optimization\n\u2022 Knowledge of mobile money support operations',
  skills = ARRAY['Customer support', 'Team management', 'Multilingual support', 'Knowledge base', 'NPS tracking'],
  experience_years = 3,
  education = E'Business, Communications, or related field'
WHERE title = 'Customer Support Lead';

-- ============================================================================
-- VERIFICATION: Check all 33 jobs were updated
-- ============================================================================
SELECT title, created_at, experience_years,
       LEFT(description, 60) AS description_preview,
       skills
FROM job_listings
ORDER BY created_at DESC;
